### ISSUE TITLE
PHP 7.0 support

### ISSUE THREAD

**Issue by marchrius** [vantoozz/proxy-scraper#1]
Hi, I've forked your repo and created a branch with php7.0 support.

If you want, I'll make a pull request

**Comment by vantoozz** [comment]
Let's have a look

**Comment by codeprof2** [comment]
wich version of this will work php 7 ?
vantoozz/proxy-scraper v1.7.0 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
